// src/components/TheHeader.vue
<template>
  <header class="bg-white shadow">
    <nav class="container-custom py-4">
      <div class="flex flex-wrap justify-between items-center gap-4 md:flex-nowrap">
        <!-- Logo部分 -->
        <div class="flex items-center">
          <router-link to="/" class="flex items-center">
            <img src="../assets/logo.jpg" alt="/" class="h-10 w-auto mr-2">
            <span class="text-xl font-bold text-red-700">台灣速食餐飲協會</span>
          </router-link>
        </div>
        
        <!-- 移動端選單按鈕 -->
        <button @click="isMenuOpen = !isMenuOpen" class="md:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path v-if="isMenuOpen" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            <path v-else stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
        
        <!-- 導航選單 -->
        <div :class="['md:flex', isMenuOpen ? 'block' : 'hidden']">
          <ul class="flex flex-col md:flex-row md:space-x-8 space-y-2 md:space-y-0">
            <li><router-link to="/" class="text-gray-700 hover:text-red-600 font-medium">首頁</router-link></li>
            <li><router-link to="/about" class="text-gray-700 hover:text-red-600 font-medium">關於協會</router-link></li>
            <li><router-link to="/leadership" class="text-gray-700 hover:text-red-600 font-medium">協會成員</router-link></li>
            <li><router-link to="/events" class="text-gray-700 hover:text-red-600 font-medium">活動資訊</router-link></li>
            <li><router-link to="/contact" class="text-gray-700 hover:text-red-600 font-medium">聯絡我們</router-link></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
</template>

<script setup>
import { ref } from 'vue';

const isMenuOpen = ref(false);
</script>

// components/TheHeader.jsx
'use client'

import { useState } from 'react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'

const navLinks = [
  { href: '/', label: '首頁' },
  { href: '/about', label: '關於協會' },
  { href: '/leadership', label: '協會成員' },
  { href: '/events', label: '活動資訊' },
  { href: '/contact', label: '聯絡我們' },
]

export default function TheHeader() {
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const pathname = usePathname()

  return (
    <header className="bg-white shadow">
      <nav className="container-custom py-4">
        <div className="flex flex-wrap justify-between items-center gap-4 md:flex-nowrap">
          <div className="flex items-center">
            <Link href="/" className="flex items-center">
              <img src="/images/logo.jpg" alt="台灣速食餐飲協會" className="h-10 w-auto mr-2" />
              <span className="text-xl font-bold text-red-700">台灣速食餐飲協會</span>
            </Link>
          </div>

          <button
            onClick={() => setIsMenuOpen(!isMenuOpen)}
            className="md:hidden"
            aria-label="選單"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              {isMenuOpen ? (
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              ) : (
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
              )}
            </svg>
          </button>

          <div className={`${isMenuOpen ? 'block' : 'hidden'} md:flex`}>
            <ul className="flex flex-col md:flex-row md:space-x-8 space-y-2 md:space-y-0">
              {navLinks.map(({ href, label }) => (
                <li key={href}>
                  <Link
                    href={href}
                    className={
                      pathname === href
                        ? 'text-red-600 font-semibold'
                        : 'text-gray-700 hover:text-red-600 font-medium'
                    }
                  >
                    {label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </nav>
    </header>
  )
}
